### ISSUE TITLE
Rotation scramblers

### ISSUE THREAD

**Issue by M0N57R0517Y** [icyflame/reddit-comp-creator#2]
Have you figured out a way to write the rotation?  Also, I feel like it's possible to rip a 2GEN or RouxGEN scrambler out of the qqtimer.net source code, I am looking for one right now.

**Comment by icyflame** [comment]
@M0N57R0517Y I kind-of tried that already. I couldn't make any sense of the code, but didn't spend much time. I hope you have better luck :+1:

**Comment by M0N57R0517Y** [comment]
Yeah, TBH neither could I.  I tried to get it, I think the third JS repo is
the most likely place it is, but I have no idea.

**Comment by icyflame** [comment]
Hmm, let me search for it in the qqtimer repo as well.

Meanwhile. @kalyan-kumar think you can write some quick JS code to write the 2GEN scrambler?

**Comment by icyflame** [comment]
Okay, got it. This is the [function](https://github.com/cubing/qqTimer/blob/mzrg/index.htm#L2173-L2202) that we need to use. [this](https://github.com/cubing/qqTimer/blob/mzrg/index.htm#L1672) is how we use this function.

Required function: [rndEl](https://github.com/cubing/qqTimer/blob/mzrg/index.htm#L1296)

Required variable `cubesuff`: [here](https://github.com/cubing/qqTimer/blob/mzrg/index.htm#L1230)

I will try to integrate this into this repo to make both 2GEN scramblers and LSE scramblers work.

**Comment by icyflame** [comment]
Fixed in #3
